version: '2.4'
services:
  matcha:
      build: .
      container_name: "matcha"
      command: "gradle run"
      mem_limit: 500m
      networks:
        - kafka-network
      depends_on:
        - kafka
      restart: always
  kafka:
      image: wurstmeister/kafka
      container_name: "kafka"
      mem_limit: 7g
      ports:
        - "9092:9092"
      hostname: kafka
      networks:
        - kafka-network
      depends_on:
        - zookeeper
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=kafka
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
        - KAFKA_LISTENERS=PLAINTEXT//0.0.0.0:9092
        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
        - KAFKA_BROKER_ID=222
      restart: always
  zookeeper:
      container_name: "zookeeper"
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
      networks:
        - kafka-network
      restart: always

networks:
  kafka-network:
    external: true