version: '2'
services:
  matcha:
      build: .
      container_name: "matcha"
      command: "gradle run"
      mem_limit: 500m
      depends_on:
        - kafka
      restart: always
  kafka:
      image: wurstmeister/kafka
      container_name: "kafka"
      mem_limit: 7g
      ports:
        - "9092:9092"
      hostname: kafka
      depends_on :
        - zookeeper
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=kafka
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_ADVERTISED_PORT=9092
      restart: always
  zookeeper:
      container_name: "zookeeper"
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
      restart: always
