version: '2.4'
services:
  matcha:
      build: .
      container_name: "matcha"
      command: "gradle run"
      mem_limit: 500m
      networks:
        - kafka-network
      depends_on:
        - kafka
      restart: always
  kafka:
      image: 'bitnami/kafka:latest'
      container_name: "kafka"
      mem_limit: 7g
      ports:
        - "9092:9092"
      hostname: kafka
      networks:
        - kafka-network
      depends_on:
        - zookeeper
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      volumes:
        - ./data/kafka:/bitnami/kafka
      restart: always
  zookeeper:
      container_name: "zookeeper"
      image: 'bitnami/zookeeper:latest'
      ports:
        - "2181:2181"
      networks:
        - kafka-network
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
      restart: always

networks:
  kafka-network:
    external: true